server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://175.178.229.38:33006/boot_websocket?serverTimezone=GMT%2B8
    username: root
    password: luoj@2023
    driver-class-name: com.mysql.cj.jdbc.Driver

